name: Create Goal Tracks

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - ".github/data/session/session_*.json"

permissions:
  contents: read
  issues: write
  repository-projects: write

jobs:
  create-issues:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: run create_goal_tracks script
        uses: actions/github-script@v7
        env:
          PROJECT_FIELD_ID: ${{ vars.PROJECT_FIELD_ID }}
          PROJECT_FIELD_STATUS_ID: ${{ vars.PROJECT_FIELD_STATUS_ID }}
          START_DATE_FIELD_ID: ${{ vars.START_DATE_FIELD_ID }}
          END_DATE_FIELD_ID: ${{ vars.END_DATE_FIELD_ID }}
          SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/create-goal-tracks.js
        with:
          github-token: ${{ secrets.GH_PAT_PLANET_DEVO_K }}
          script: |
            const { default: run } = await import(process.env.SCRIPT_FULL_PATH);
            await run({ github, context, core });
