name: Notifier Discussion

on:
  discussion:
    types: [created]
  workflow_dispatch:

permissions:
  discussions: read
  contents: read

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: send discord notification
        uses: actions/github-script@v7
        env:
          DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CHANNEL_ID_POST}}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN_NOTIFIER }}
          SCRIPT_FULL_PATH: ${{ github.workspace }}/.github/scripts/senders/notifier-discussion.js
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: notify } = await import(process.env.SCRIPT_FULL_PATH);
            await notify({ github, context, core, data: context.payload.discussion });
