name: Trigger Discussion Notification

on:
  discussion:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger automation repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_PLANET_DEVO_K }}
          repository: planet-devo-k/automation
          event-type: stackit-discussion-created
          client-payload: '{"discussion": ${{ toJson(github.event.discussion) }}}'
